name: action-genai-issue-labeller
description: Labels GitHub issues based on their content using GitHub Models.
inputs:
  github_token:
    description: "GitHub token with `models: read` permission at least."
    required: true
  github_issue:
    description: GitHub issue number to use when generating comments.
  debug:
    description: Enable debug logging.
    required: false
branding:
    icon: "map-pin"
    color: "yellow"
runs:
  using: docker
  image: Dockerfile
