name: "genai-issue-labeller"
description: action
inputs:
  github_token:
    description: "GitHub token with `models: read` and `issues: write` permission at least."
    required: true
  github_issue:
    description: GitHub issue number to use when generating comments.
  debug:
    description: Enable debug logging.
    required: false
runs:
  using: docker
  image: Dockerfile
